service: chefin-organizations-api

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-monorepo
  # - serverless-plugin-optimize

# package:
#   individually: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  createOrganizationWithUser:
    description: Cria a Organization junto com um usuário inicial
    handler: src/handlers/organizations/create-org-with-user.handler
    events:
      - http:
          method: POST
          path: /organizations
